wordcloud1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
 	path('', include('wc.urls')),
       
]

wordcloud1/wc/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('home/', views.index),
    path('aboutus/',views.aboutus),
    path('contact/',views.contact),
    
    ]

wordcloud1/wordcloud1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
 	path('', include('wc.urls')),
       
]

wordcloud1/wc/models.py
from django.db import models

# Create your models here.


wordcloud1/wc/forms.py
from django import forms


class textInput(forms.Form):
	text = forms.CharField(label = 'text', widget=forms.Textarea)
	typechoices = [('Type1','Square shape'), ('Type2','Heart shape'), ('Type3','Dimond shape')]
	maskType = forms.CharField(label = 'Type', widget = forms.RadioSelect(choices = typechoices))

wordcloud1/wc/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render_to_response
from .forms import textInput
from wordcloud import WordCloud, STOPWORDS
from PIL import Image
import urllib
import requests
import matplotlib.pyplot as plt
import numpy as npy

def generate_wordcloud(words, mask):
    word_cloud = WordCloud(width = 512, height = 512, background_color='white', stopwords=STOPWORDS, mask=mask).generate(words)
    plt.figure(figsize=(8,6),facecolor = 'white', edgecolor='blue')
    plt.imshow(word_cloud)
    plt.axis('off')
    plt.tight_layout(pad=0)
    plt.show()
    print('generated')

def create_word_cloud(string, Type):
	print(Type)
	print('OOKk')
	if Type == 1:
		maskArray = npy.array(Image.open(r"wc/static/square.png"))
	elif Type == 2:
		maskArray = npy.array(Image.open(r"wc/static/heart.jpg"))
	elif Type == 3:
		maskArray = npy.array(Image.open(r"wc/static/diamond.jpg"))
	cloud = WordCloud(background_color = "white",max_words = 200,margin=0, mask = maskArray, stopwords = set(STOPWORDS))
	cloud.generate(string)
	cloud.to_file(r"wc/static/pic.png")

def index(request):
    if (request.method == 'POST'):
    	print('POSTED')
    	form = textInput(request.POST)
    	if form.is_valid():
    		text = form.cleaned_data['text']
    		Type = form.cleaned_data['maskType']
    		dataset = text.lower()
    		print(text)
    		print(Type)
    		if Type == 'Type1':
    			create_word_cloud(string = dataset, Type = 1)
    		elif Type == 'Type2':
    			create_word_cloud(string = dataset, Type = 2)
    		elif Type == 'Type3':
    			create_word_cloud(string = dataset, Type = 3)
    		
    	return render(request,'wc/image.html')
    else:
    	form = textInput()
    	args = {'form': form}
    	return render(request,'wc/ak.html', args)
def aboutus(request):
	return render_to_response('wc/aboutus.html')
def contact(request):
	return render_to_response('wc/contact.html')


wordcloud1/wc/templates/wc/aboutus.html
<!DOCTYPE html>
<html style="background-color:LightGray;">
<!-- <html background-image = url("a.jpg")> -->
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
body, html {
  height: 100%;
  margin: 0;
}


body, html {
  height: 100%;
}

.bg { 
  /* The image used */
  background-image: url("http://hashtag-bg.com/wp-content/uploads/2018/08/cool-background-images-resume-57-backgrounds-free-jpeg-png-format-download.jpg");

  /* Full height */
  height: 100%; 

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}


</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}
.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
</style>
</head>
<body>
	<div class="topnav">
				<a href="/home">Home</a>
				<a href="/contact">Contact </a>
				<a class="active" href="/aboutus">About us</a>
				<br>
	</div>
<!-- <h4><a href="/home">Back</a></h4> -->
<h1>CREATED BY </h1><br>
<h3>1. Praveen Kotwani<h3>
<h3>2. Neeti Mishra</h3>
<h3>3. Anjali Joshi</h3>
</body>
</html>

wordcloud1/wc/templates/wc/ak.html
<html background-image = url("a.jpg")>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
body, html {
  height: 100%;
  margin: 0;
}


body, html {
  height: 100%;
}

.bg { 
  /* The image used */
  background-image: url("http://hashtag-bg.com/wp-content/uploads/2018/08/cool-background-images-resume-57-backgrounds-free-jpeg-png-format-download.jpg");

  /* Full height */
  height: 100%; 

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
li{
  list-style: none;
}


</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #2c3e50;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: #2c3e50;
}
.topnav a.active {
  background-color: #2980b9;
  color: white;
}
</style>
</head>
<body style="background-image: url('https://wallpapercave.com/wp/SMyrO7b.jpg'); background-size: cover; " >
<div class="topnav">
  <a class="active" href="/home">Home</a>
  <a href="/contact">Contact </a>
  <a href="/aboutus">About us</a>
  <br>

</div>





</div>
<center><h1 class="mt-3">CREATE YOUR OWN WORDCLOUD</h1></center>


<form method = "POST"><br />
  {% if form %}
{% csrf_token %}
     <center><h3> Enter Text: </h3><textarea style="background-color:#f0f0f0;" name="text" cols="100" rows="10" required id="id_text">
</textarea></center>
<center> <button class="btn btn-secondary mt-2"><a href="" style="color: #fff;">Reset</a></button></center>
      <div class="px-5"><h1>Select Shape:</h1>
      <ul id="id_maskType ">
    <li><label style="font-size:30px;" for="id_maskType_0"><input type="radio" name="maskType" value="Type1" required id="id_maskType_0">
 Square shape</label>

</li>
    <li><label style="font-size:30px;" for="id_maskType_1"><input type="radio" name="maskType" value="Type2" required id="id_maskType_1">
 Heart shape</label>

</li>
    <li><label style="font-size:30px;" for="id_maskType_2"><input type="radio" name="maskType" value="Type3" required id="id_maskType_2">
 Dimond shape</label></div>

   <center><button style="font-size:30px;" type = "submit" class="btn btn-primary" >Create Word Cloud </button></center> 

  {% endif %}
</form>
<div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html> 

wordcloud1/wc/templates/wc/contact.html
<!DOCTYPE html>
<html style="background-color:LightGray;">
<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<style>
		body, html {
		  height: 100%;
		  margin: 0;
		}
		
		
		body, html {
		  height: 100%;
		}
		
		.bg { 
		  /* The image used */
		  background-image: url("http://hashtag-bg.com/wp-content/uploads/2018/08/cool-background-images-resume-57-backgrounds-free-jpeg-png-format-download.jpg");
		
		  /* Full height */
		  height: 100%; 
		
		  /* Center and scale the image nicely */
		  background-position: center;
		  background-repeat: no-repeat;
		  background-size: cover;
		}
		
		
		</style>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<style>
		body {
		  margin: 0;
		  font-family: Arial, Helvetica, sans-serif;
		}
		
		.topnav {
		  overflow: hidden;
		  background-color: #333;
		}
		
		.topnav a {
		  float: left;
		  color: #f2f2f2;
		  text-align: center;
		  padding: 14px 16px;
		  text-decoration: none;
		  font-size: 17px;
		}
		
		.topnav a:hover {
		  background-color: #ddd;
		  color: black;
		}
		.topnav a.active {
		  background-color: #4CAF50;
		  color: white;
		}
		</style>
		</head>
<body>
	<div class="topnav">
				<a href="/home">Home</a>
				<a class="active" href="/contact">Contact </a>
				<a href="/aboutus">About us</a>
				<br>		  
	</div>
<!-- <h4><a href="/home">Back</a></h4> -->
<h1>Phone no. :- 0000000000</h1><br>
</body>
</html>

wordcloud1/wc/templates/wc/image.html
{% load static %}
<!DOCTYPE html>
<html style="background-color:LightGray;">
		<html background-image = url("a.jpg")>
		<head>
				<meta name="viewport" content="width=device-width, initial-scale=1">
				<style>
				body, html {
				  height: 100%;
				  margin: 0;
				}
				
				
				body, html {
				  height: 100%;
				}
				
				.bg { 
				  /* The image used */
				  background-image: url("http://hashtag-bg.com/wp-content/uploads/2018/08/cool-background-images-resume-57-backgrounds-free-jpeg-png-format-download.jpg");
				
				  /* Full height */
				  height: 100%; 
				
				  /* Center and scale the image nicely */
				  background-position: center;
				  background-repeat: no-repeat;
				  background-size: cover;
				}
				
				
				</style>
				<meta name="viewport" content="width=device-width, initial-scale=1">
				<style>
				body {
				  margin: 0;
				  font-family: Arial, Helvetica, sans-serif;
				}
				
				.topnav {
				  overflow: hidden;
				  background-color: #333;
				}
				
				.topnav a {
				  float: left;
				  color: #f2f2f2;
				  text-align: center;
				  padding: 14px 16px;
				  text-decoration: none;
				  font-size: 17px;
				}
				
				.topnav a:hover {
				  background-color: #ddd;
				  color: black;
				}
				.topnav a.active {
				  background-color: #4CAF50;
				  color: white;
				}
				</style>
				</head>
<body>
		<div class="topnav">
				<a href="/home">Home</a>
				<a href="/contact">Contact </a>
				<a href="/aboutus">About us</a>
				<br>
			  
			  </div>
	<!-- <h3><a href="">Back</a></h3> -->
	<h1><U><B><center>~WORD CLOUD~</center></B></U><br></h1>
	<center><img src="{% static 'pic.png' %}" height="450" width="450"></center>
	<center><button><a href ="/static/pic.png" download>Download Image</a></button></center>
</body>
</html>